/*
 * Copyright (C) 2021 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_penguinpeakutils_VsockClientImpl */

#ifndef _Included_com_intel_penguinpeakutils_VsockClientImpl
#define _Included_com_intel_penguinpeakutils_VsockClientImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_penguinpeakutils_VsockClientImpl
 * Method:    socketCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_penguinpeakutils_VsockClientImpl_socketCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_penguinpeakutils_VsockClientImpl
 * Method:    connect
 * Signature: (Lcom/intel/penguinpeakutils/VsockAddress;)V
 */
JNIEXPORT void JNICALL Java_com_intel_penguinpeakutils_VsockClientImpl_connect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_intel_penguinpeakutils_VsockClientImpl
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_penguinpeakutils_VsockClientImpl_close
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_penguinpeakutils_VsockClientImpl
 * Method:    write
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_intel_penguinpeakutils_VsockClientImpl_write
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_intel_penguinpeakutils_VsockClientImpl
 * Method:    read
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_intel_penguinpeakutils_VsockClientImpl_read
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_intel_penguinpeakutils_VsockClientImpl
 * Method:    writeInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_intel_penguinpeakutils_VsockClientImpl_writeInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_intel_penguinpeakutils_VsockClientImpl
 * Method:    readInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_penguinpeakutils_VsockClientImpl_readInt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
